---
rt_apache_service: apache2
rt_apache_user: 'www-data'
mysql_root_password: ''
rt_package_dependencies:
  - 'autoconf'
  - 'build-essential'
  - 'cpanminus'
  - 'curl'
  - 'libexpat-dev'
  - 'libssl-dev'
  - 'libz-dev'
  - 'git'
  - 'gnupg2'
  - 'graphviz'
  - 'perl'
  - 'multiwatch'
  - 'starlet'
  - 'w3m'
  - 'libapache2-mod-fcgid'
  - 'libbusiness-hours-perl'
  - 'libapache-session-wrapper-perl'
  - 'libcgi-emulate-psgi-perl'
  - 'libcgi-psgi-perl'
  - 'libcss-minifier-xs-perl'
  - 'libcss-squish-perl'
  - 'libmoosex-emulate-class-accessor-fast-perl'
  - 'libconvert-color-perl'
  - 'libcrypt-eksblowfish-perl'
  - 'libdbix-searchbuilder-perl=1.71*'  # Needs backports
  - 'libdata-guid-perl'
  - 'libdata-ical-perl'
  - 'libdata-page-pageset-perl'
  - 'libdate-extract-perl'
  - 'libdate-manip-perl'
  - 'libemail-address-perl'
  - 'libemail-address-list-perl'
  - 'libencode-detect-perl'
  - 'libencode-hanextra-perl'
  - 'libhtml-formatexternal-perl'
  - 'libhtml-formattext-withlinks-andtables-perl'
  - 'libhtml-gumbo-perl'
  - 'libhtml-mason-psgihandler-perl'
  - 'libhtml-quoted-perl'
  - 'libhtml-rewriteattributes-perl'
  - 'libhtml-scrubber-perl'
  - 'libipc-run3-perl'
  - 'libjson-perl'
  - 'libjavascript-minifier-xs-perl'
  - 'liblocale-maketext-fuzzy-perl'
  - 'liblocale-maketext-lexicon-perl'
  - 'liblog-dispatch-perl'
  - 'libmime-types-perl'
  - 'libtest-email-perl'
  - 'libmodule-path-perl'
  - 'libmodule-refresh-perl'
  - 'libmodule-versions-report-perl'
  - 'libmoosex-nonmoose-perl'
  - 'libmoosex-role-parameterized-perl'
  - 'libnet-cidr-perl'
  - 'libnetaddr-ip-perl'
  - 'libparallel-forkmanager-perl'
  - 'libplack-perl'
  - 'libpod-parser-perl'
  - 'libregexp-common-net-cidr-perl'
  - 'librole-basic-perl'
  - 'libscope-upper-perl'
  - 'libsymbol-global-name-perl'
  - 'libtext-password-pronounceable-perl'
  - 'libtext-quoted-perl'
  - 'libtext-wikiformat-perl'
  - 'libtext-worddiff-perl'
  - 'libtext-wrapper-perl'
  - 'libtime-parsedate-perl'
  - 'libtree-simple-perl'
  - 'libuniversal-require-perl'
  - 'libweb-machine-perl'
  - 'libxml-rss-perl'
  - 'libnet-ldap-perl'
  - 'libfile-which-perl'
  - 'libgnupg-interface-perl=1.02*'  # Requires backports
  - 'libperlio-eol-perl'
  - 'libgraphviz-perl'
  - 'libdbd-mysql-perl'
  - 'libcrypt-x509-perl'
  - 'libnet-ip-perl'
  - 'libpath-dispatcher-perl'
  - 'libregexp-ipv6-perl'
